In [11]:
import numpy as np

## Arrays

In [2]:
a = np.array([1, 4, 5, 8], float)

In [4]:
print(a, type(a))

[1. 4. 5. 8.] <class 'numpy.ndarray'>


In [12]:
a[:2]

array([1., 4.])

In [13]:
a[3]

8.0

In [14]:
a[0]=5.

In [15]:
a

array([5., 4., 5., 8.])

In [16]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)

In [17]:
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [22]:
a[0,2]

3.0

In [23]:
a[1,:]

array([4., 5., 6.])

In [24]:
a[-1,-2]

5.0

In [25]:
a.shape

(2, 3)

In [26]:
a.dtype

dtype('float64')

In [27]:
len(a)

2

In [28]:
2 in a

True

In [29]:
0 in a

False

In [33]:
b = a.reshape((3,2))

In [34]:
b

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [35]:
c = a.copy()
a[0,0] = 4

In [36]:
a

array([[4., 2., 3.],
       [4., 5., 6.]])

In [37]:
c

array([[1., 2., 3.],
       [4., 5., 6.]])

In [38]:
b

array([[4., 2.],
       [3., 4.],
       [5., 6.]])

In [39]:
a.tolist()

[[4.0, 2.0, 3.0], [4.0, 5.0, 6.0]]

In [40]:
list(a)

[array([4., 2., 3.]), array([4., 5., 6.])]

In [44]:
bin = a.tostring()
bin

b'\x00\x00\x00\x00\x00\x00\x10@\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x10@\x00\x00\x00\x00\x00\x00\x14@\x00\x00\x00\x00\x00\x00\x18@'

In [45]:
np.fromstring(bin)

/Users/tobias/miniconda3/envs/ml/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  """Entry point for launching an IPython kernel.


array([4., 2., 3., 4., 5., 6.])

In [47]:
b.fill(0)
b

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [59]:
a = np.array(range(6), float)
a

array([0., 1., 2., 3., 4., 5.])

In [67]:
a = a.reshape((2, 3))
a

array([[0., 1., 2.],
       [3., 4., 5.]])

In [65]:
b = a.transpose()
b

array([[0., 3.],
       [1., 4.],
       [2., 5.]])

In [68]:
a.flatten()

array([0., 1., 2., 3., 4., 5.])

In [71]:
np.concatenate((a,b.reshape((2,3))))

array([[0., 1., 2.],
       [3., 4., 5.],
       [0., 3., 1.],
       [4., 2., 5.]])

In [75]:
np.concatenate((a,b.reshape((2,3))), axis=1)

array([[0., 1., 2., 0., 3., 1.],
       [3., 4., 5., 4., 2., 5.]])

In [76]:
a

array([[0., 1., 2.],
       [3., 4., 5.]])

In [92]:
b = a[:,np.newaxis]
b.shape

(2, 1, 3)

In [93]:
b

array([[[0., 1., 2.]],

       [[3., 4., 5.]]])

## other ways, create arrays

In [95]:
np.arange(5, dtype=float)

array([0., 1., 2., 3., 4.])

In [96]:
np.arange(1, 6, 2, dtype=int)

array([1, 3, 5])

In [97]:
np.ones((2,3), dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [98]:
np.zeros(7, dtype=int)

array([0, 0, 0, 0, 0, 0, 0])

In [99]:
np.zeros_like(a)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [100]:
np.ones_like(a)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [101]:
np.identity(4, dtype=float)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [102]:
np.eye(4, k=1, dtype=float)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

## mathematics

In [103]:
a = np.array([1,2,3], float)
b = np.array([5,2,6], float)

In [104]:
a+b

array([6., 4., 9.])

In [105]:
a-b

array([-4.,  0., -3.])

In [106]:
a*b

array([ 5.,  4., 18.])

In [107]:
a/b

array([0.2, 1. , 0.5])

In [110]:
a%b

array([1., 0., 3.])

In [111]:
a**b

array([  1.,   4., 729.])

In [112]:
a = np.array([[1,2], [3,4]], float)
b = np.array([[2,0], [1,3]], float)
a * b

array([[ 2.,  0.],
       [ 3., 12.]])

In [113]:
a = np.array([1.1, 1.5, 1.9], float)
np.rint(a)

array([1., 2., 2.])

## interations

In [122]:
for x in a:
    print(x)

1.1
1.5
1.9


In [123]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
for x in a:
    print(x)

[1. 2.]
[3. 4.]
[5. 6.]


In [124]:
for (x,y) in a:
    print(x,y)

1.0 2.0
3.0 4.0
5.0 6.0


## operations

In [125]:
a.sum()

21.0

In [127]:
np.prod(a)

720.0

In [128]:
a.mean()

3.5

In [129]:
np.var(a)

2.9166666666666665

In [130]:
a.std()

1.707825127659933

In [132]:
a.min()

1.0

In [134]:
a.argmin() # index

0

In [135]:
a.mean(axis=0)

array([3., 4.])

In [136]:
a.min(axis=1)

array([1., 3., 5.])

In [140]:
a.clip(2,4)

array([[2., 2.],
       [3., 4.],
       [4., 4.]])

In [141]:
np.unique(a)

array([1., 2., 3., 4., 5., 6.])

In [142]:
a.diagonal()

array([1., 4.])

## comparison

In [145]:
b = b.reshape(3,2)
a > b

array([[False,  True],
       [ True,  True],
       [ True,  True]])

In [146]:
a <= b

array([[ True, False],
       [False, False],
       [False, False]])

In [147]:
a > 5

array([[False, False],
       [False, False],
       [False,  True]])

In [158]:
c = (a > b).flatten()
any(c)

True

In [159]:
all(c)

False

In [160]:
np.logical_and(a > 0, a < 3)

array([[ True,  True],
       [False, False],
       [False, False]])

In [161]:
np.logical_or(a > 4, a < 2)

array([[ True, False],
       [False, False],
       [ True,  True]])

In [163]:
np.logical_not(a == 4)

array([[ True,  True],
       [ True, False],
       [ True,  True]])

In [165]:
np.where(a > 3, 'it\'s true', 'it\'s false') # bool, if true if false

array([["it's false", "it's false"],
       ["it's false", "it's true"],
       ["it's true", "it's true"]], dtype='<U10')

In [169]:
a.nonzero()

(array([0, 0, 1, 1, 2, 2]), array([0, 1, 0, 1, 0, 1]))

In [171]:
a = np.array([1, np.NaN, np.Inf], float)
a

array([ 1., nan, inf])

In [172]:
np.isnan(a)

array([False,  True, False])

In [173]:
np.isfinite(a)

array([ True, False, False])